### ISSUE TITLE
Firefox needs an upgrade

### ISSUE THREAD

**Issue by 0xhaven** [chromakode/xkcdfools#1]
On line 222, I believe you wanted:

```
($.browser.name == 'firefox' && $.browser.versionX < 3)
```

not:

```
($.browser.name == 'firefox' || $.browser.versionX < 3)
```

Unless firefox and version numbers <3 are inherently inferior.

**Comment by chromakode** [comment]
Firefox versions below 3.0 have a bug displaying alt-text that annoyed xkcd users. That's the reason behind this code. :)

**Comment by TorKlingberg** [comment]
Yes, so it should be && instead of ||.

**Comment by chromakode** [comment]
D'oh! Sorry, you're right. Thanks for your patience. :)
