### ISSUE TITLE
Include a scrollbar?

### ISSUE THREAD

**Issue by mwarrenus** [chromakode/xkcdfools#10]
Scrolling the content with Page Up and Page Down is OK, but could unixkcd include a scrollbar as well?  Thanks.

**Comment by chromakode** [comment]
That would be cheating! :-)

**Comment by sgbeal** [comment]
@mwarrenus: You can accomplish this (_cough_cheat_cough_) by changing the CSS. Tinker with the various overflow settings to get an effect you like (if overflow is on for all elements it looks miserable). Google for "css overflow" for much more detail.
