### ISSUE TITLE
TerminalShell.print() should accept an array

### ISSUE THREAD

**Issue by sgbeal** [chromakode/xkcdfools#12]
This seems to behave more like print() does in most JS shells (SpiderMonkey, v8, and friends):

```
print: function(text) {
    if (!text) {
        $('#display').append($('<div>'));
    } else if( text instanceof jQuery ) {
                $('#display').append(text);
    } else {
                var av = Array.prototype.slice.apply(arguments,[0]);
                $('#display').append($('<p>').text(av.join(' ')));
    }
    this.jumpToBottom();
},
```

the (instanceof jQuery) bit should be extended to include DOM elements, i think. Ideally, it should use a loop (instead of av.join(' ')) so that each element can be evaluated for its type individually. But i'm too tired for that ;).

**Comment by chromakode** [comment]
Beautiful! Thanks for a much better implementation. I wasn't sure of the right way to check for jQuery objects, so I went with the safe approach. Thanks for teaching me something. :)
