### ISSUE TITLE
Should su change "login" prefix?

### ISSUE THREAD

**Issue by katanacrimson** [chromakode/xkcdfools#23]
After using "su", shouldn't the prefix for the interface commands change from 
    guest@xkcd:/$
to
    root@xkcd:/$
?

**Comment by enderandrew** [comment]
I'm not really a JS coder, but couldn't you get rid of the su oneliner and instead do something like this:

TerminalShell.commands['su'] = function(terminal) {
    TerminalShell.sudo = true;
    terminal.print('God mode activated. Remember, with great power comes great ... aw, screw it, go have fun.');
    this.config.prompt = 'root@console:/$ ';
};
