### ISSUE TITLE
The noscript GUI Interface link tag links to a 404 page

### ISSUE THREAD

**Issue by tomsinger** [chromakode/xkcdfools#4]
The link to foo in the link 'GUI Interface' in the noscript tag leads to a 404 response.

Proposed fix:
    - <a href="foo">GUI Interface</a>
    + <a href="/1/">GUI Interface</a>

**Comment by chromakode** [comment]
Ha, meant to update that before we went live. Thanks for catching it!

I've fixed this, and it'll go up soon.
